// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tung8.data;

namespace tung8.Migrations
{
    /* [DbContext(typeof(FirstAppDemoDbContext))]
     partial class FirstAppDemoDbContextModelSnapshot : ModelSnapshot
     {
         protected override void BuildModel(ModelBuilder modelBuilder)
         {
 #pragma warning disable 612, 618
             modelBuilder
                 .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                 .HasAnnotation("Relational:MaxIdentifierLength", 128)
                 .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

             modelBuilder.Entity("tung8.Models.Employee", b =>
                 {
                     b.Property<int>("ID")
                         .ValueGeneratedOnAdd()
                         .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                     b.Property<string>("Name");

                     b.HasKey("ID");

                     b.ToTable("Employees");
                 });
 #pragma warning restore 612, 618
         }
     }*/
    public partial class v1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.CreateTable(name: "Employee", columns: table => new {
                Id = table.Column<int>(nullable: false)
                  .Annotation("SqlServer:ValueGenerationStrategy",
                  SqlServerValueGenerationStrategy.IdentityColumn),
                Name = table.Column<string>(nullable: true)
            },
            constraints: table => {
                table.PrimaryKey("PK_Employee", x => x.Id);
            });
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable("Employee");
        }
    }
}
